adding project init
Kayphaz007/Task-scheduler pull request #1
Opened 2023-02-20 13:27 UTC by Kayphaz007

2023-02-22 12:51 UTC, dolad requested changes

2023-02-22 12:51 UTC, dolad commented on .vscode/settings.json
> +}
remove please

2023-02-22 12:51 UTC, dolad commented on src/index.html
> +          <img src="./imgs/banana.jpg" alt="" />
can you remove the images, the images is not part of the task

2023-02-22 12:51 UTC, dolad commented on src/index.html
> +          <img src="./imgs/banana.jpg" alt="" />
Rules number always stick to instruction in engineering

2023-02-22 12:56 UTC, Kayphaz007 commented on .vscode/settings.json
> +}
allright

2023-02-22 13:52 UTC, Kayphaz007 commented
i have deleted the images folder and vscode settings. @dolad

2023-02-22 16:11 UTC, dolad commented
1 more images

2023-02-28 15:47 UTC, Kayphaz007 commented
i have remove the un necessary images and created card template @dolad

2023-02-28 21:14 UTC, dolad requested changes

2023-02-28 21:14 UTC, dolad commented on src/index.html
> +        </div>
you are misusing divs, take a look at tags like sections;
[https://dev.to/kenbellows/stop-using-so-many-divs-an-intro-to-semantic-html-3i9i](url)

2023-02-28 21:14 UTC, dolad commented on src/index.js
> +insertionSort([2,1,9,76,4])
remove please

2023-03-01 10:45 UTC, Kayphaz007 commented
I have fixed the divs misused @dolad

2023-03-01 13:08 UTC, dolad approved these changes

2023-03-01 13:08 UTC, dolad commented on src/index.css
> +}
this should be in the body, collapse as one

2023-03-01 13:08 UTC, dolad commented on src/index.css
> +}
@Kayphaz007 please make this changes before you merged

2023-03-01 15:05 UTC, Kayphaz007 commented on src/index.css
> +}
allright its done

2023-03-01 15:08 UTC, merged